databases:
  - name: interior_DB
    databaseName: interior_db
    user: kohei
    region: singapore
services:
  - type: web
    name: kohei
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: interior_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false